version: "3.9"

services:
  # ───────────── Hadoop ─────────────
  namenode:
    image: bde2020/hadoop-namenode:latest
    container_name: hadoop-namenode
    environment:
      CLUSTER_NAME: crr-lmp-hadoop
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    ports:
      - "9870:9870"     # NameNode UI

  datanode:
    image: bde2020/hadoop-datanode:latest
    container_name: hadoop-datanode
    environment:
      CLUSTER_NAME: crr-lmp-hadoop
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
      HDFS_CONF_dfs_replication: "1"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    ports:
      - "9864:9864"     # DataNode UI

  # ───────────── Spark ──────────────
  spark-master:
    image: bitnami/spark:3.5
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_EXTRA_CLASSPATH: /opt/bitnami/spark/jars/spark-cassandra-connector_2.12-3.5.0.jar
    volumes:
      - spark_master:/bitnami/spark
      - ./:/opt/work
    depends_on:
      - namenode
    ports:
      - "8080:8080"     # Spark Master UI
      - "7077:7077"     # Spark cluster port

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_MEMORY: 3G
      SPARK_EXTRA_CLASSPATH: /opt/bitnami/spark/jars/spark-cassandra-connector_2.12-3.5.0.jar
    volumes:
      - spark_worker:/bitnami/spark
      - ./:/opt/work
    depends_on:
      - spark-master

  # ─────────── Cassandra ────────────
  cassandra:
    image: cassandra:5
    container_name: cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: crr-lmp-cluster
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    ports:
      - "9042:9042"     # CQL

  # ─────────── Jupyter ──────────────
  jupyter:
    image: jupyter/pyspark-notebook:python-3.10
    container_name: jupyter
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      SPARK_MASTER: spark://spark-master:7077
      PYSPARK_PYTHON: python
      PYSPARK_DRIVER_PYTHON: jupyter
      PYSPARK_DRIVER_PYTHON_OPTS: "lab --LabApp.token='' --ip=0.0.0.0"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
      - cassandra
    ports:
      - "8888:8888"

volumes:
  hadoop_namenode:
  hadoop_datanode:
  spark_master:
  spark_worker:
  cassandra_data: